[package]
name = "rust-ml"
version = "0.1.0"
edition = "2024"

[dependencies.windows-sys]
version = "0.59" # Use the latest 2026 version
features = [
    "Win32_System_Memory", 
    "Win32_Foundation",
    "Win32_System_SystemInformation"
]